### ISSUE TITLE
R code not updated

### ISSUE THREAD

**Issue by kkami1115** [sonial/KniMet#2]
The CheckInstallLoad() function of the R Source code that obtains cdf file and performs preprocessing has not been updated, so BiocManager is not used to install the R package derived from Bioconductor.
Since this repository manages versions in .knwf format, I don't know how to change only the relevant part, so I set up an issue.
I prepared an R code. How can I help you?
[KniMet_readCDFandPreprocessing.txt](https://github.com/sonial/KniMet/files/3564266/KniMet_readCDFandPreprocessing.txt)

**Comment by sonial** [comment]
Thanks for pointing out this issue! 
I edited your version of the CheckInstallLoad() function so that it installs BiocManager only if not already present.
This updated version can be found in KniMet v1.2.6.

Cheers,
Sonia
